In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


import warnings
warnings.filterwarnings('ignore')

In [4]:
df = pd.read_csv('/home/khoim/hcmus_projects/shapG/examples/data/lung_cancer_mortality_data_large_v2.csv')

In [5]:
#check the head of dataset
df.head()

,id,age,gender,country,diagnosis_date,cancer_stage,beginning_of_treatment_date,family_history,smoking_status,bmi,cholesterol_level,hypertension,asthma,cirrhosis,other_cancer,treatment_type,end_treatment_date,survived
0,1,64.0,Female,Germany,2016-04-07,Stage III,2016-04-21,No,Never Smoked,31.1,257,1,1,0,0,Combined,2017-11-15,0
1,2,50.0,Male,Czech Republic,2023-04-22,Stage III,2023-05-02,Yes,Passive Smoker,25.9,208,1,0,0,0,Radiation,2024-04-25,0
2,3,65.0,Male,Romania,2023-04-07,Stage IV,2023-04-12,No,Never Smoked,18.9,193,0,0,0,0,Surgery,2025-03-11,0
3,4,51.0,Female,Latvia,2016-02-07,Stage III,2016-02-13,Yes,Former Smoker,34.6,249,1,1,1,0,Surgery,2017-04-14,1
4,5,37.0,Male,Greece,2023-12-01,Stage I,2023-12-03,Yes,Never Smoked,40.2,262,0,0,0,0,Chemotherapy,2024-09-20,0

In [6]:
#Exploring the dataset by different methods
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3250000 entries, 0 to 3249999
Data columns (total 18 columns):
 #   Column                       Dtype
---  ------                       -----
 0   id                           int64
 1   age                          float64
 2   gender                       object
 3   country                      object
 4   diagnosis_date               object
 5   cancer_stage                 object
 6   beginning_of_treatment_date  object
 7   family_history               object
 8   smoking_status               object
 9   bmi                          float64
 10  cholesterol_level            int64
 11  hypertension                 int64
 12  asthma                       int64
 13  cirrhosis                    int64
 14  other_cancer                 int64
 15  treatment_type               object
 16  end_treatment_date           object
 17  survived                     int64
dtypes: float64(2), int64(7), object(9)
memory usage: 446.3+ MB

In [7]:
#Check the columns in dataset
df.columns

Index(['id', 'age', 'gender', 'country', 'diagnosis_date', 'cancer_stage',
       'beginning_of_treatment_date', 'family_history', 'smoking_status',
       'bmi', 'cholesterol_level', 'hypertension', 'asthma', 'cirrhosis',
       'other_cancer', 'treatment_type', 'end_treatment_date', 'survived'],
      dtype='object')

In [8]:
#shape define the columns and rows of dataset
#18 Columns & 325000 rows
df.shape

(3250000, 18)

In [9]:
#checking for null values
df.isnull().sum()

id                             0
age                            0
gender                         0
country                        0
diagnosis_date                 0
cancer_stage                   0
beginning_of_treatment_date    0
family_history                 0
smoking_status                 0
bmi                            0
cholesterol_level              0
hypertension                   0
asthma                         0
cirrhosis                      0
other_cancer                   0
treatment_type                 0
end_treatment_date             0
survived                       0
dtype: int64

In [10]:
#checking for duplicate values
df.duplicated().sum()

np.int64(0)

In [11]:
df1= df.copy()

In [12]:
# Checking the survival rate variation by country
# Grouping by 'country' and calculating the mean survival rate for each country
country_survival_rates = df1.groupby('country')['survived'].mean()

# Displaying the survival rates for each country
country_survival_rates.sort_values(ascending=False)

country
Austria           0.222682
Bulgaria          0.221396
Latvia            0.221105
Cyprus            0.221066
Hungary           0.220413
Ireland           0.220324
Czech Republic    0.220165
Denmark           0.220159
Finland           0.219994
Romania           0.219926
Luxembourg        0.219917
Netherlands       0.219826
Belgium           0.219401
Spain             0.219328
Sweden            0.219246
Slovenia          0.219238
Germany           0.219120
Poland            0.218988
Slovakia          0.218967
Estonia           0.218884
Lithuania         0.218805
France            0.218780
Italy             0.218747
Greece            0.218508
Malta             0.218134
Portugal          0.218126
Croatia           0.217966
Name: survived, dtype: float64

In [13]:
from sklearn.preprocessing import LabelEncoder


# Creating a LabelEncoder object
label_encoder = LabelEncoder()

# Columns to apply label encoding on (only for binary or ordinal categories)
columns_to_label_encode = ['family_history','cancer_stage', 'gender',  'smoking_status','treatment_type']

# Applying label encoding to each column
for col in columns_to_label_encode:
    df1[col] = label_encoder.fit_transform(df1[col])

# Applying one-hot encoding for 'treatment_type'
#df1 = pd.get_dummies(df1, columns=['treatment_type'], drop_first=True)

# Display the updated dataframe
print(df.head())

   id   age  gender         country diagnosis_date cancer_stage  \
0   1  64.0  Female         Germany     2016-04-07    Stage III
1   2  50.0    Male  Czech Republic     2023-04-22    Stage III
2   3  65.0    Male         Romania     2023-04-07     Stage IV
3   4  51.0  Female          Latvia     2016-02-07    Stage III
4   5  37.0    Male          Greece     2023-12-01      Stage I

  beginning_of_treatment_date family_history  smoking_status   bmi  \
0                  2016-04-21             No    Never Smoked  31.1
1                  2023-05-02            Yes  Passive Smoker  25.9
2                  2023-04-12             No    Never Smoked  18.9
3                  2016-02-13            Yes   Former Smoker  34.6
4                  2023-12-03            Yes    Never Smoked  40.2

   cholesterol_level  hypertension  asthma  cirrhosis  other_cancer  \
0                257             1       1          0             0
1                208             1       0          0             0
2                193             0       0          0             0
3                249             1       1          1             0
4                262             0       0          0             0

  treatment_type end_treatment_date  survived
0       Combined         2017-11-15         0
1      Radiation         2024-04-25         0
2        Surgery         2025-03-11         0
3        Surgery         2017-04-14         1
4   Chemotherapy         2024-09-20         0

In [14]:
# Display the updated dataframe
print(df1.head())

   id   age  gender         country diagnosis_date  cancer_stage  \
0   1  64.0       0         Germany     2016-04-07             2
1   2  50.0       1  Czech Republic     2023-04-22             2
2   3  65.0       1         Romania     2023-04-07             3
3   4  51.0       0          Latvia     2016-02-07             2
4   5  37.0       1          Greece     2023-12-01             0

  beginning_of_treatment_date  family_history  smoking_status   bmi  \
0                  2016-04-21               0               2  31.1
1                  2023-05-02               1               3  25.9
2                  2023-04-12               0               2  18.9
3                  2016-02-13               1               1  34.6
4                  2023-12-03               1               2  40.2

   cholesterol_level  hypertension  asthma  cirrhosis  other_cancer  \
0                257             1       1          0             0
1                208             1       0          0             0
2                193             0       0          0             0
3                249             1       1          1             0
4                262             0       0          0             0

   treatment_type end_treatment_date  survived
0               1         2017-11-15         0
1               2         2024-04-25         0
2               3         2025-03-11         0
3               3         2017-04-14         1
4               0         2024-09-20         0

In [17]:
# Dropping the 'id' and 'country' columns
df1 = df1.drop(columns=['id', 'country'])

# Display the updated dataframe
df1.head()

KeyError: "['id', 'country'] not found in axis"

In [18]:
#shape define the columns and rows of dataset
#18 Columns & 325000 rows
df1.shape

(3250000, 16)

In [19]:
# Ensure both 'diagnosis_date' and 'beginning_of_treatment_date' are in datetime format
df1['diagnosis_date'] = pd.to_datetime(df1['diagnosis_date'])
df1['beginning_of_treatment_date'] = pd.to_datetime(df1['beginning_of_treatment_date'])

# Calculate the treatment delay (time between diagnosis and start of treatment)
df1['treatment_delay_days'] = (df1['beginning_of_treatment_date'] - df1['diagnosis_date']).dt.days

# Drop the original date columns if they're no longer needed
df1 = df1.drop(columns=['diagnosis_date'])

# Display the updated dataframe
print(df1.head())

    age  gender  cancer_stage beginning_of_treatment_date  family_history  \
0  64.0       0             2                  2016-04-21               0
1  50.0       1             2                  2023-05-02               1
2  65.0       1             3                  2023-04-12               0
3  51.0       0             2                  2016-02-13               1
4  37.0       1             0                  2023-12-03               1

   smoking_status   bmi  cholesterol_level  hypertension  asthma  cirrhosis  \
0               2  31.1                257             1       1          0
1               3  25.9                208             1       0          0
2               2  18.9                193             0       0          0
3               1  34.6                249             1       1          1
4               2  40.2                262             0       0          0

   other_cancer  treatment_type end_treatment_date  survived  \
0             0               1         2017-11-15         0
1             0               2         2024-04-25         0
2             0               3         2025-03-11         0
3             0               3         2017-04-14         1
4             0               0         2024-09-20         0

   treatment_delay_days
0                    14
1                    10
2                     5
3                     6
4                     2

In [20]:
# Ensure the columns are in datetime format
df1['beginning_of_treatment_date'] = pd.to_datetime(df1['beginning_of_treatment_date'])
df1['end_treatment_date'] = pd.to_datetime(df1['end_treatment_date'])

# Calculate the duration of treatment in days
df1['treatment_duration_days'] = (df1['end_treatment_date'] - df1['beginning_of_treatment_date']).dt.days

# Drop the original date columns
df1 = df1.drop(columns=['beginning_of_treatment_date', 'end_treatment_date'])

# Display the updated dataframe
print(df1.head())

    age  gender  cancer_stage  family_history  smoking_status   bmi  \
0  64.0       0             2               0               2  31.1
1  50.0       1             2               1               3  25.9
2  65.0       1             3               0               2  18.9
3  51.0       0             2               1               1  34.6
4  37.0       1             0               1               2  40.2

   cholesterol_level  hypertension  asthma  cirrhosis  other_cancer  \
0                257             1       1          0             0
1                208             1       0          0             0
2                193             0       0          0             0
3                249             1       1          1             0
4                262             0       0          0             0

   treatment_type  survived  treatment_delay_days  treatment_duration_days
0               1         0                    14                      573
1               2         0                    10                      359
2               3         0                     5                      699
3               3         1                     6                      426
4               0         0                     2                      292

In [21]:
df1.shape

(3250000, 15)

In [22]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3250000 entries, 0 to 3249999
Data columns (total 15 columns):
 #   Column                   Dtype
---  ------                   -----
 0   age                      float64
 1   gender                   int64
 2   cancer_stage             int64
 3   family_history           int64
 4   smoking_status           int64
 5   bmi                      float64
 6   cholesterol_level        int64
 7   hypertension             int64
 8   asthma                   int64
 9   cirrhosis                int64
 10  other_cancer             int64
 11  treatment_type           int64
 12  survived                 int64
 13  treatment_delay_days     int64
 14  treatment_duration_days  int64
dtypes: float64(2), int64(13)
memory usage: 371.9 MB

In [29]:
subset_df = df1.iloc[:200000]

# Save to a new CSV file
subset_df.to_csv('/home/khoim/hcmus_projects/shapG/examples/data/subset_data.csv', index=False)

In [30]:
subset_df

,age,gender,cancer_stage,family_history,smoking_status,bmi,cholesterol_level,hypertension,asthma,cirrhosis,other_cancer,treatment_type,survived,treatment_delay_days,treatment_duration_days
0,64.0,0,2,0,2,31.1,257,1,1,0,0,1,0,14,573
1,50.0,1,2,1,3,25.9,208,1,0,0,0,2,0,10,359
2,65.0,1,3,0,2,18.9,193,0,0,0,0,3,0,5,699
3,51.0,0,2,1,1,34.6,249,1,1,1,0,3,1,6,426
4,37.0,1,0,1,2,40.2,262,0,0,0,0,0,0,2,292
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199995,75.0,1,1,1,3,35.0,295,1,1,1,0,3,1,1,707
199996,48.0,0,3,1,2,22.6,222,1,0,0,0,1,0,5,677
199997,49.0,1,0,1,1,17.4,187,1,1,0,0,0,0,28,416
199998,55.0,0,1,0,2,33.1,269,0,0,0,0,3,0,13,704
199999,67.0,0,2,1,3,29.1,234,1,1,0,0,2,0,3,314